org.gradle.caching=true
group=io.ballerina.stdlib
version=1.10.2-SNAPSHOT

ballerinaGradlePluginVersion=4.0.0
spotbugsPluginVersion=6.5.1
shadowJarPluginVersion=7.1.2
downloadPluginVersion=5.4.0
releasePluginVersion=3.1.0
checkstylePluginVersion=10.12.0
jacocoVersion=0.8.10
testngVersion=7.7.1
gsonVersion=2.7
jacksonDatabindVersion=2.17.2

ballerinaLangVersion=2201.14.0-SNAPSHOT
stdlibIoVersion=1.8.0

balScanVersion=0.10.0
