[package]
org = "ballerina"
name = "os"
version = "@toml.version@"
authors = ["Ballerina"]
keywords = ["environment"]
repository = "https://github.com/ballerina-platform/module-ballerina-os"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.7.0"

[platform.java17]
graalvmCompatible = true

[[platform.java17.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "os-native"
version = "@toml.version@"
path = "../native/build/libs/os-native-@project.version@.jar"

[[platform.java17.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "io-native"
version = "@io.version@"
path = "./lib/io-native-@io.native.version@.jar"

[[platform.java17.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "os-test-utils"
version = "@toml.version@"
path = "../test-utils/build/libs/os-test-utils-@project.version@.jar"
